--- 
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: jobs-client 
  labels: 
    app: job-api
spec: 
  replicas: 2 
  selector: 
    matchLabels: 
      app: job-api 
  template: 
    metadata: 
      labels: 
        app: <...> 
    spec: 
      containers: 
        - name: <...> 
          imagePullPolicy: Always 
          image: <...> 
          command: <...> 
          env: 
          - <...> 
          ports: 
          - <...> 