--- 
apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  name: hello-aan1-data 
spec: 
  accessModes: 
    - ReadWriteOnce 
  storageClassName: standard
  resources: 
    requests: 
      storage: 1Gi 