--- 
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: aan1-test-meteorite-landings-app
  labels: 
    app: aan1-meteorite-landings-app
    username: aan1
    env: test
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: aan1-meteorite-landings-app
  template: 
    metadata: 
      labels: 
        app: aan1-meteorite-landings-app
        username: aan1
        env: test
    spec: 
      containers: 
        - name: aan1-meteorite-landings-app
          imagePullPolicy: Always
          image: aan1/hw6-app:latest
          env:
          - name: FLASK_APP
            value: "app.py"
          ports:
          - name: http
            containerPort: 5000