--- 
apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  name: aan1-landings-app-data
  labels: 
    app: landings-app-data
    username: aan1
    env: test
spec: 
  accessModes: 
    - ReadWriteOnce 
  # No nfs storage available. Using native standard storage class.
  storageClassName: standard
  resources: 
    requests: 
      storage: 1Gi 