--- 
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: hello-pvc-deployment 
  labels: 
    app: hello-pvc-app 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: hello-pvc-app 
  template: 
    metadata: 
      labels: 
        app: hello-pvc-app 
    spec: 
      containers: 
        - name: hellos 
          image: ubuntu:18.04 
          command: ['sh', '-c', 'echo "Hello, Kubernetes!" >> /data/out.txt && sleep 3600'] 
          volumeMounts: 
            - name: hello-aan1-data
              mountPath: "/data" 
      volumes: 
        - name: hello-aan1-data
          persistentVolumeClaim: 
            claimName: hello-aan1-data