--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: test-flask-server 
  labels:
    username: aan1
    env: test
spec: 
  type: ClusterIP 
  selector: 
    app: aan1-meteorite-landings-app
  ports: 
  - name: aan1-meteorite-landings-app
    port: 5000
    targetPort: 5000 