--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: test-redis-server 
  labels:
    username: aan1
    env: test
spec: 
  type: ClusterIP 
  selector: 
    app: aan1-meteorite-landings-app-data
  ports: 
  - name: aan1-meteorite-landings-app-data
    port: 6379
    targetPort: 6379 